// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedLibraries.Database;

#nullable disable

namespace SharedLibraries.Migrations
{
    [DbContext(typeof(DatabaseModel))]
    [Migration("20260215213432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLibraries.model.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("SharedLibraries.model.CompanyUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateExit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "IsActive");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("SharedLibraries.model.CounterpartyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Counterparties");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupFiles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupsFiles");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCloseDepartment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAlert")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CounterpartyId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardFiles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<Guid>("GuardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.ToTable("GuardsFiles");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumDog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumDog2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OhronnaComp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("ResPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("StrokDii")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StrokDii2")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardNotes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.ToTable("GuardsNotes");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseFiles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<Guid>("SubleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubleaseId");

                    b.ToTable("SubleasesFiles");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AktDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ContractEndDate2")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ContractSigningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Done")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<double>("RentalFee")
                        .HasColumnType("double precision");

                    b.Property<double>("RentalFee2")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Subleases");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseNotes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("SubleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubleaseId");

                    b.ToTable("SubleasesNotes");
                });

            modelBuilder.Entity("SharedLibraries.model.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharedLibraries.model.CompanyUser", b =>
                {
                    b.HasOne("SharedLibraries.model.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibraries.model.Users", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedLibraries.model.CounterpartyModel", b =>
                {
                    b.HasOne("SharedLibraries.model.Company", "Company")
                        .WithMany("Counterparties")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupFiles", b =>
                {
                    b.HasOne("SharedLibraries.model.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupModel", b =>
                {
                    b.HasOne("SharedLibraries.model.Company", "Company")
                        .WithMany("Groups")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLibraries.model.CounterpartyModel", "Counterparty")
                        .WithMany("Groups")
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardFiles", b =>
                {
                    b.HasOne("SharedLibraries.model.GuardModel", "Guard")
                        .WithMany("GuardFiles")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardModel", b =>
                {
                    b.HasOne("SharedLibraries.model.GroupModel", "Group")
                        .WithMany("Guard")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardNotes", b =>
                {
                    b.HasOne("SharedLibraries.model.GuardModel", "Guard")
                        .WithMany("GuardNotes")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseFiles", b =>
                {
                    b.HasOne("SharedLibraries.model.SubleaseModel", "Sublease")
                        .WithMany("SubleaseFiles")
                        .HasForeignKey("SubleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sublease");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseModel", b =>
                {
                    b.HasOne("SharedLibraries.model.GroupModel", "Group")
                        .WithMany("Sublease")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseNotes", b =>
                {
                    b.HasOne("SharedLibraries.model.SubleaseModel", "Sublease")
                        .WithMany("SubleaseNotes")
                        .HasForeignKey("SubleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sublease");
                });

            modelBuilder.Entity("SharedLibraries.model.Company", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("Counterparties");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SharedLibraries.model.CounterpartyModel", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupModel", b =>
                {
                    b.Navigation("Guard");

                    b.Navigation("Sublease");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardModel", b =>
                {
                    b.Navigation("GuardFiles");

                    b.Navigation("GuardNotes");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseModel", b =>
                {
                    b.Navigation("SubleaseFiles");

                    b.Navigation("SubleaseNotes");
                });

            modelBuilder.Entity("SharedLibraries.model.Users", b =>
                {
                    b.Navigation("CompanyUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
