// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedLibraries.Database;

#nullable disable

namespace SharedLibraries.Migrations
{
    [DbContext(typeof(DatabaseModel))]
    [Migration("20260407103655_RentInfoForGroups")]
    partial class RentInfoForGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLibraries.model.CounterpartyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Counterparties");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateCloseDepartment")
                        .HasColumnType("date");

                    b.Property<bool>("IsAlert")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("integer");

                    b.Property<int>("RentType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupRentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("RentTypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("GroupRentInfos");

                    b.HasDiscriminator<string>("RentTypeDiscriminator").HasValue("GroupRentInfo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SharedLibraries.model.GuardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumDog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumDog2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OhronnaComp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("ResPerson")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StrokDii")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StrokDii2")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseFiles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<Guid>("SubleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubleaseId");

                    b.ToTable("SubleasesFiles");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AktDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ContractEndDate2")
                        .HasColumnType("date");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ContractSigningDate")
                        .HasColumnType("date");

                    b.Property<bool?>("Done")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsContinuation")
                        .HasColumnType("boolean");

                    b.Property<double>("RentalFee")
                        .HasColumnType("double precision");

                    b.Property<double>("RentalFee2")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Subleases");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseNotes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("SubleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubleaseId");

                    b.ToTable("SubleasesNotes");
                });

            modelBuilder.Entity("SharedLibraries.model.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharedLibraries.model.RentType1Info", b =>
                {
                    b.HasBaseType("SharedLibraries.model.GroupRentInfo");

                    b.Property<string>("CertNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CertNumber");

                    b.Property<string>("Issued")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesCert")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Type1");
                });

            modelBuilder.Entity("SharedLibraries.model.RentType2Info", b =>
                {
                    b.HasBaseType("SharedLibraries.model.GroupRentInfo");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Num");

                    b.HasDiscriminator().HasValue("Type2");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseRentInfo", b =>
                {
                    b.HasBaseType("SharedLibraries.model.GroupRentInfo");

                    b.Property<string>("Edrpou")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Person")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RentNumber");

                    b.Property<string>("Rnokpp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue("Sublease");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupModel", b =>
                {
                    b.HasOne("SharedLibraries.model.CounterpartyModel", "Counterparty")
                        .WithMany("Groups")
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupRentInfo", b =>
                {
                    b.HasOne("SharedLibraries.model.GroupModel", "Group")
                        .WithOne("RentInfo")
                        .HasForeignKey("SharedLibraries.model.GroupRentInfo", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SharedLibraries.model.GuardModel", b =>
                {
                    b.HasOne("SharedLibraries.model.GroupModel", "Group")
                        .WithMany("Guard")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseFiles", b =>
                {
                    b.HasOne("SharedLibraries.model.SubleaseModel", "Sublease")
                        .WithMany("SubleaseFiles")
                        .HasForeignKey("SubleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sublease");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseModel", b =>
                {
                    b.HasOne("SharedLibraries.model.GroupModel", "Group")
                        .WithMany("Sublease")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseNotes", b =>
                {
                    b.HasOne("SharedLibraries.model.SubleaseModel", "Sublease")
                        .WithMany("SubleaseNotes")
                        .HasForeignKey("SubleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sublease");
                });

            modelBuilder.Entity("SharedLibraries.model.CounterpartyModel", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SharedLibraries.model.GroupModel", b =>
                {
                    b.Navigation("Guard");

                    b.Navigation("RentInfo");

                    b.Navigation("Sublease");
                });

            modelBuilder.Entity("SharedLibraries.model.SubleaseModel", b =>
                {
                    b.Navigation("SubleaseFiles");

                    b.Navigation("SubleaseNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
